

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/childcare
      driver-class-name: org.h2.Driver
      username: sa
      password:
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

# 로그 레벨 설정
logging:
  level:
    root: INFO
    org.springframework.context: DEBUG
    euljiro.project: DEBUG



# kakao api
api:
  kakao:
    userInfo_url : https://kapi.kakao.com/v2/user/me
  apple:
    auth:
      token-url: https://appleid.apple.com/auth/token
      public-key-url: https://appleid.apple.com/auth/keys
    redirect-uri: ${APPLE_REDIRECT_URL}
    iss: https://appleid.apple.com
    aud: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    key:
      id: ${APPLE_KEY_ID}
      private-key: appleprivate
      path: classpath:/apple/AuthKey_${APPLE_KEY_ID}.p8


# jwt
jwt:
  secret : jwtSecret


# FIREBASE
fcm:
  file_path: firebase/childcareproducts.json
  url: https://fcm.googleapis.com/v1/projects/childcareproducts-97db1/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: yughel-pushtest