

spring:
  datasource:
    url : jdbc:mysql://database.cp8w6mwqoz4r.ap-northeast-2.rds.amazonaws.com:3306/childcare
    username : admin
    password : adminadmin
    driver-class-name : com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis.yqij3h.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

# 로그 레벨 설정
logging:
  level:
    root: INFO
    org.springframework.context: DEBUG
    euljiro.project: DEBUG



# api
api:
  kakao:
    userInfo_url : https://kapi.kakao.com/v2/user/me


# jwt
jwt:
  secret : jwtSecret
