

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/childcare
      driver-class-name: org.h2.Driver
      username: sa
      password:
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG



# api
api:
  kakao:
    userInfo_url : https://kapi.kakao.com/v2/user/me


# jwt
jwt:
  secret : jwtSecret
